pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                sh 'echo "Setting up environment..."'
                //sh 'sudo apt update'
                //sh 'sudo apt install -y python3 python3-pip python3-venv'
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate'
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Download data') {
            steps {
                sh 'python3 scripts/download_data.py'
            }
        }
        stage('Train model') {
            steps {
                sh 'python3 scripts/train_model.py'
            }
        }
        stage('Test Model') {
            steps {
                sh 'python3 scripts/test_model.py'
            }
        }
        stage('Make prediction') {
            steps {
                sh 'python3 scripts/make_prediction.py'
            }
        }
    }
    post {
        always {
            sh 'echo "Pipeline completed"'
        }
    }
}
